"""
Immutable domain models for trading signals.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any


class SignalAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class Signal:
    """
    An immutable trading signal generated by a strategy.

    Attributes:
        symbol:    Market symbol, e.g. 'BTC/USDT'.
        action:    buy / sell / hold.
        strength:  Conviction level 0.0 (weak) – 1.0 (strong).
        reason:    Human-readable explanation.
        timestamp: When the signal was generated.
        metadata:  Optional extra context (indicator values, etc.).
    """

    __slots__ = ("symbol", "action", "strength", "reason", "timestamp", "metadata")

    def __init__(
        self,
        symbol: str,
        action: SignalAction,
        strength: float,
        reason: str,
        timestamp: datetime,
        metadata: dict[str, Any] | None = None,
    ) -> None:
        object.__setattr__(self, "symbol", symbol)
        object.__setattr__(self, "action", action)
        object.__setattr__(self, "strength", max(0.0, min(1.0, strength)))
        object.__setattr__(self, "reason", reason)
        object.__setattr__(self, "timestamp", timestamp)
        object.__setattr__(self, "metadata", metadata or {})

    def __setattr__(self, name: str, value: object) -> None:
        raise AttributeError("Signal is immutable")

    def __repr__(self) -> str:
        return (
            f"Signal(symbol={self.symbol!r}, action={self.action.value!r}, "
            f"strength={self.strength:.2f}, reason={self.reason!r})"
        )

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Signal):
            return NotImplemented
        return (
            self.symbol == other.symbol
            and self.action == other.action
            and abs(self.strength - other.strength) < 1e-9
            and self.reason == other.reason
            and self.timestamp == other.timestamp
        )

    def is_actionable(self) -> bool:
        """Return True when the signal recommends an actual trade (not HOLD)."""
        return self.action != SignalAction.HOLD
